Convert a Package file for Swift 4
vapor/fluent-provider pull request #34
Opened 2017-09-24 16:35 UTC by lightwave

Provide a package file with Swift 4 syntax

2017-09-24 16:56 UTC, 0xTim requested changes
Can you update the CI scripts as well to test and build on Swift 4 as well as Swift 3?

2017-09-24 16:56 UTC, 0xTim commented on Package@swift-4.swift
> +        .package(url: "https://github.com/vapor/fluent.git", .upToNextMajor(from: "2.0.0")),
Can you mark fluent as from 2.4.0

2017-09-24 16:56 UTC, 0xTim commented on Package@swift-4.swift
> +        .package(url: "https://github.com/vapor/vapor.git", .upToNextMajor(from: "2.0.0")),
And Vapor should be from 2.1.0

2017-09-24 18:04 UTC, 0xTim commented
Also, whilst I’m being pedantic, could you update the README to point to Swift 4 as well?

2017-09-25 14:03 UTC, lightwave commented
Updated and pushed changes.

Thanks
--
Chris

On Sep 24, 2017, 2:04 PM -0400, Tim <notifications@github.com>, wrote:
> Also, whilst I’m being pedantic, could you update the README to point to Swift 4 as well?
> —
> You are receiving this because you authored the thread.
> Reply to this email directly, view it on GitHub, or mute the thread.

2017-09-25 18:16 UTC, 0xTim approved these changes

2017-09-25 18:16 UTC, 0xTim commented
LGTM - @tanner0101 ?

2017-09-25 18:33 UTC, tanner0101 commented
thanks :)

2017-09-25 18:33 UTC, merged

2017-09-25 22:01 UTC, lightwave commented
Tim, I missed the CI scripts, but where is the CI scripts in fluent-provider… I’m not seeing it.

Thanks
--
Chris

On Sep 24, 2017, 12:56 PM -0400, Tim <notifications@github.com>, wrote:
> @0xTim requested changes on this pull request.
> Can you update the CI scripts as well to test and build on Swift 4 as well as Swift 3?
> In Package@swift-4.swift:
> > @@ -0,0 +1,17 @@
> +// swift-tools-version:4.0
> +import PackageDescription
> +
> +let package = Package(
> +    name: "FluentProvider",
> +    products: [
> +        .library(name: "FluentProvider", targets: ["FluentProvider"]),
> +    ],
> +    dependencies: [
> +        .package(url: "https://github.com/vapor/fluent.git", .upToNextMajor(from: "2.0.0")),
> Can you mark fluent as from 2.4.0
> In Package@swift-4.swift:
> > @@ -0,0 +1,17 @@
> +// swift-tools-version:4.0
> +import PackageDescription
> +
> +let package = Package(
> +    name: "FluentProvider",
> +    products: [
> +        .library(name: "FluentProvider", targets: ["FluentProvider"]),
> +    ],
> +    dependencies: [
> +        .package(url: "https://github.com/vapor/fluent.git", .upToNextMajor(from: "2.0.0")),
> +        .package(url: "https://github.com/vapor/vapor.git", .upToNextMajor(from: "2.0.0")),
> And Vapor should be from 2.1.0
> —
> You are receiving this because you authored the thread.
> Reply to this email directly, view it on GitHub, or mute the thread.

2017-09-25 22:32 UTC, 0xTim commented
They can be found here https://github.com/vapor/fluent-provider/blob/master/circle.yml

They already run on Swift 4, but it’s probably worth doing another PR to also run the tests in 3.1, like the main repo - https://github.com/vapor/vapor/blob/master/circle.yml